import type {Metadata} from "next";
import "./globals.css";
import '@mantine/core/styles.css'
import {ColorSchemeScript, MantineProvider} from '@mantine/core';
import React from "react";
import {AppContainer} from "@/Module/Core/Component";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html dir={"rtl"} lang="fa">
        <head>
            <ColorSchemeScript/>
        </head>
        <body>
        <MantineProvider>
            <AppContainer>{children}</AppContainer>
        </MantineProvider>
        </body>
        </html>
    );
}
